//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.12 at 03:49:10 PM BRT 
//


package com.fiap.cobranca.model.jaxb.boleto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vencimento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cpf" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processamento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="recebedora" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="valor" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="pago" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="deposito" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "vencimento",
    "cpf",
    "processamento",
    "recebedora",
    "valor",
    "pago",
    "deposito"
})
@XmlRootElement(name = "boleto")
public class Boleto {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String vencimento;
    @XmlElement(required = true)
    protected String cpf;
    @XmlElement(required = true)
    protected String processamento;
    @XmlElement(required = true)
    protected String recebedora;
    protected double valor;
    protected boolean pago;
    protected boolean deposito;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the vencimento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVencimento() {
        return vencimento;
    }

    /**
     * Sets the value of the vencimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVencimento(String value) {
        this.vencimento = value;
    }

    /**
     * Gets the value of the cpf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpf() {
        return cpf;
    }

    /**
     * Sets the value of the cpf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpf(String value) {
        this.cpf = value;
    }

    /**
     * Gets the value of the processamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessamento() {
        return processamento;
    }

    /**
     * Sets the value of the processamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessamento(String value) {
        this.processamento = value;
    }

    /**
     * Gets the value of the recebedora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecebedora() {
        return recebedora;
    }

    /**
     * Sets the value of the recebedora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecebedora(String value) {
        this.recebedora = value;
    }

    /**
     * Gets the value of the valor property.
     * 
     */
    public double getValor() {
        return valor;
    }

    /**
     * Sets the value of the valor property.
     * 
     */
    public void setValor(double value) {
        this.valor = value;
    }

    /**
     * Gets the value of the pago property.
     * 
     */
    public boolean isPago() {
        return pago;
    }

    /**
     * Sets the value of the pago property.
     * 
     */
    public void setPago(boolean value) {
        this.pago = value;
    }

    /**
     * Gets the value of the deposito property.
     * 
     */
    public boolean isDeposito() {
        return deposito;
    }

    /**
     * Sets the value of the deposito property.
     * 
     */
    public void setDeposito(boolean value) {
        this.deposito = value;
    }

}
