//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.23 at 10:35:34 PM BRT 
//


package com.fiap.faturamento.jaxb.notafiscal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numero_nf" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vencimento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cpf" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="valor" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="impostos" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="transportadora" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="produto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emissao" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numeroNf",
    "vencimento",
    "cpf",
    "valor",
    "impostos",
    "transportadora",
    "produto",
    "emissao"
})
@XmlRootElement(name = "notafiscal")
public class Notafiscal {

    @XmlElement(name = "numero_nf", required = true)
    protected String numeroNf;
    @XmlElement(required = true)
    protected String vencimento;
    @XmlElement(required = true)
    protected String cpf;
    protected double valor;
    protected double impostos;
    @XmlElement(required = true)
    protected String transportadora;
    @XmlElement(required = true)
    protected String produto;
    @XmlElement(required = true)
    protected String emissao;

    /**
     * Gets the value of the numeroNf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroNf() {
        return numeroNf;
    }

    /**
     * Sets the value of the numeroNf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroNf(String value) {
        this.numeroNf = value;
    }

    /**
     * Gets the value of the vencimento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVencimento() {
        return vencimento;
    }

    /**
     * Sets the value of the vencimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVencimento(String value) {
        this.vencimento = value;
    }

    /**
     * Gets the value of the cpf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpf() {
        return cpf;
    }

    /**
     * Sets the value of the cpf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpf(String value) {
        this.cpf = value;
    }

    /**
     * Gets the value of the valor property.
     * 
     */
    public double getValor() {
        return valor;
    }

    /**
     * Sets the value of the valor property.
     * 
     */
    public void setValor(double value) {
        this.valor = value;
    }

    /**
     * Gets the value of the impostos property.
     * 
     */
    public double getImpostos() {
        return impostos;
    }

    /**
     * Sets the value of the impostos property.
     * 
     */
    public void setImpostos(double value) {
        this.impostos = value;
    }

    /**
     * Gets the value of the transportadora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportadora() {
        return transportadora;
    }

    /**
     * Sets the value of the transportadora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportadora(String value) {
        this.transportadora = value;
    }

    /**
     * Gets the value of the produto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduto() {
        return produto;
    }

    /**
     * Sets the value of the produto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduto(String value) {
        this.produto = value;
    }

    /**
     * Gets the value of the emissao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmissao() {
        return emissao;
    }

    /**
     * Sets the value of the emissao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmissao(String value) {
        this.emissao = value;
    }

}
